language: node_js
node_js:
  - "16"

services:
  - docker

before_install:
  - pyenv install 3.6.15
  - pyenv global 3.6.15
  - if [[ -v DOCKERHUB_TOKEN ]]; then echo "${DOCKERHUB_TOKEN}" | docker login -u "icdevops" --password-stdin; fi
  - mkdir -p /tmp/json-schema

script:
  # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --low; else npx audit-ci --low || true; fi
  - npm run lint
  - npm test
  - docker build --rm -t "quay.io/razee/mustachetemplate:${TRAVIS_COMMIT}" .
  - if [ -n "${TRAVIS_TAG}" ]; then docker tag quay.io/razee/mustachetemplate:${TRAVIS_COMMIT} quay.io/razee/mustachetemplate:${TRAVIS_TAG}; fi
  - docker images
  - ./build/process-template.sh kubernetes/MustacheTemplate/resource.yaml >/tmp/resource.yaml
  - if [[ "${TRAVIS_TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
  - git clone https://github.com/yannh/kubeconform.git /tmp/kubeconform
  - pip install --user --quiet -r /tmp/kubeconform/scripts/requirements.txt
  - python /tmp/kubeconform/scripts/openapi2jsonschema.py /tmp/resource.yaml
  - mv mustachetemplate_*.json /tmp/json-schema/

before_deploy:
  - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io

deploy:
  # Deploy alpha builds
  - provider: script
    script: docker push "quay.io/razee/mustachetemplate:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$

  # Deploy released builds
  - provider: script
    script: docker push "quay.io/razee/mustachetemplate:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    api_key: "${GITHUB_TOKEN}"
    name: "${TRAVIS_TAG}"
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/json-schema/mustachetemplate_*.json
    skip_cleanup: true
    api_key: "${GITHUB_TOKEN}"
    name: "${TRAVIS_TAG}"
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: npm
    email: "${NPMJS_EMAIL}"
    api_key: "${NPMJS_API_KEY}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
