apiVersion: v1
kind: List
metadata:
  name: mustachetemplate-controller-list
  annotations:
    version: "{{TRAVIS_COMMIT}}"
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
type: array
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mustachetemplate-controller
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      labels:
        razee/watch-resource: "lite"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mustachetemplate-controller
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: mustachetemplate-controller
            razee/watch-resource: "lite"
          name: mustachetemplate-controller
        spec:
          serviceAccountName: razeedeploy-sa
          containers:
          - image: "quay.io/razee/mustachetemplate:{{TRAVIS_TAG}}"
            resources:
              limits:
                memory: 200Mi
                cpu: 100m
              requests:
                memory: 75Mi
                cpu: 40m
            imagePullPolicy: Always
            name: mustachetemplate-controller
            livenessProbe:
              exec:
                command:
                - sh/liveness.sh
              initialDelaySeconds: 30
              periodSeconds: 150
              timeoutSeconds: 30
              failureThreshold: 1
            volumeMounts:
            - mountPath: /usr/src/app/config
              name: razeedeploy-config
          volumes:
          - name: razeedeploy-config
            configMap:
              name: razeedeploy-config
              defaultMode: 420
              optional: true
  - apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      # name must match the spec fields below, and be in the form: <plural>.<group>
      name: mustachetemplates.deploy.razee.io
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    spec:
      # group name to use for REST API: /apis/<group>/<version>
      group: deploy.razee.io
      # list of versions supported by this CustomResourceDefinition
      versions:
        - name: v1alpha1
          # Each version can be enabled/disabled by Served flag.
          served: true
          # One and only one version must be marked as the storage version.
          storage: true
      # either Namespaced or Cluster
      scope: Namespaced
      names:
        # plural name to be used in the URL: /apis/<group>/<version>/<plural>
        plural: mustachetemplates
        # singular name to be used as an alias on the CLI and for display
        singular: mustachetemplate
        # kind is normally the CamelCased singular type. Your resource manifests use this.
        kind: MustacheTemplate
        # shortNames allow shorter string to match your resource on the CLI
        shortNames:
        - mtp
      subresources:
        # status enables the status subresource.
        status: {}
      validation:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                custom-tags:
                  type: array
                  maxItems: 2
                  minItems: 2
                  items:
                    type: string
                    maxLength: 3
                    minLength: 2
              allOf:
              - anyOf:
                - type: object
                  required: [envFrom]
                  properties:
                    envFrom:
                      type: array
                      items:
                        type: object
                        allOf:
                          - type: object
                            properties:
                              optional:
                                type: boolean
                          - oneOf:
                            - type: object
                              required: [configMapRef]
                              properties:
                                configMapRef:
                                  type: object
                                  required: [name]
                                  properties:
                                    name:
                                      type: string
                            - type: object
                              required: [secretMapRef]
                              properties:
                                secretMapRef:
                                  type: object
                                  required: [name]
                                  properties:
                                    name:
                                      type: string
                            - type: object
                              required: [genericMapRef]
                              properties:
                                genericMapRef:
                                  type: object
                                  required: [apiVersion, kind, name]
                                  properties:
                                    apiVersion:
                                      type: string
                                    kind:
                                      type: string
                                    name:
                                      type: string
                - type: object
                  required: [env]
                  properties:
                    env:
                      type: array
                      items:
                        allOf:
                        - type: object
                          required: [name]
                          properties:
                            name:
                              type: string
                            optional:
                              type: boolean
                        - oneOf:
                          # static value
                          - type: object
                            required: [value]
                            properties:
                              value:
                                type: string
                          - type: object
                            required: [value]
                            properties:
                              value:
                                type: number
                          - type: object
                            required: [value]
                            properties:
                              value:
                                type: boolean
                          # valueFrom
                          - type: object
                            required: [valueFrom]
                            properties:
                              valueFrom:
                                type: object
                                required: [secretKeyRef]
                                properties:
                                  secretKeyRef:
                                    type: object
                                    required: [name, key]
                                    properties:
                                      name:
                                        type: string
                                      key:
                                        type: string
                                      type:
                                        type: string
                          - type: object
                            required: [valueFrom]
                            properties:
                              valueFrom:
                                type: object
                                required: [configMapKeyRef]
                                properties:
                                  configMapKeyRef:
                                    type: object
                                    required: [name, key]
                                    properties:
                                      name:
                                        type: string
                                      key:
                                        type: string
                                      type:
                                        type: string
                          - type: object
                            required: [valueFrom]
                            properties:
                              valueFrom:
                                type: object
                                required: [genericKeyRef]
                                properties:
                                  genericKeyRef:
                                    type: object
                                    required: [apiVersion, kind, name, key]
                                    properties:
                                      apiVersion:
                                        type: string
                                      kind:
                                        type: string
                                      name:
                                        type: string
                                      key:
                                        type: string
                                      type:
                                        type: string
              - type: object
                required: [templates]
                properties:
                  templates:
                    type: array
                    items:
                      oneOf:
                      - type: string
                      - type: object
                        required: [kind, apiVersion, metadata]
                        properties:
                          kind:
                            type: string
                          apiVersion:
                            type: string
                          metadata:
                            type: object
                            required: [name]
                            properties:
                              name:
                                type: string
                              namespace:
                                type: string
